### ISSUE TITLE
问一下这个框架可以和getx混用的么

### ISSUE THREAD

**Issue by xieqi520** [tal-tech/d_stack#19]

**Comment by xieqi520** [comment]
这个路由的格式必须按照demo的样式写么

**Comment by whqfor** [comment]
getx 只是做状态同步的话可以使用，如果用来做路由管理的话，getx不能管理native的路由，需要进行改造，dstack的核心思想是记录节点，只要节点能准确的记录到即可。
路由格式可以进行一层封装，最终内部调用的样式就是demo的样子，如果觉得麻烦可以写一个转换层进行封装

**Comment by xieqi520** [comment]
原生之前的调整可以不用这个DStack么，直接用原生的跳转

**Comment by whqfor** [comment]
可以，对原生跳转，使用runtime做了导航栏的跳转记录，原生的相互跳转不需要改动，flutter打开原生需要使用api
