### ISSUE TITLE
flutter1->native1->flutter2->native1->flutter1  在flutter1上注册的部分第三方插件失效

### ISSUE THREAD

**Issue by chenchunhao9125** [tal-tech/d_stack#2]

**Comment by RebortY** [comment]
> _No description provided._

可以提供更详细的信息么？

**Comment by chenchunhao9125** [comment]
能否在demo 中加入第三方插件的调用  比如 image_picker 或者自定义的plugin

**Comment by whqfor** [comment]
可以的，我们尽快加上

**Comment by whqfor** [comment]
经过验证应该不存在无法注册的问题。针对image_picker这个库问题，最早的时候我们也遇见过，和混合栈无关，image_picker会在程序启动的时候获取rootViewController，使用SB加载页面的时候Flutter加载会有延迟导致image_picker获取不到跟控制器。
